import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import { homePath, ticketsPath} from "@/paths";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex justify-between py-2.5 px-0 w-full" >
          <div>
          <Link href={homePath}>Home</Link>
          </div>
          <div>
            <Link href={ticketsPath}>Tickets</Link>
          </div>
        </nav>
        <main className="max-w-2xl mx-auto py-24 px-0">{children}</main>
      </body>
    </html>
  );
}
